substitutions:
  device_name: growatt-mod-10k-tl3-x
  friendly_name: Growatt (Standart)
  device_description: Growatt MOD 10k TL3-X (Standart)
  modbus_controller_id: controller1
  modbus_update_interval: 15s #normal update
  skip_updates_slow: "6"  #how many times to skip normal update for slow updating sensors
  skip_updates_1min: "4"  #how many times to skip normal update for slow updating sensors
  skip_updates_10min: "20"  #how many times to skip normal update for slow updating sensors
  update_fast: "15s"
  update_normal: "60s"
  update_slow: "300s"


#########################################################################################################
### FROM https://community.home-assistant.io/t/esphome-modbus-growatt-shinewifi-s/369171/181?page=9 ###
### https://github.com/klatremis/esphome-for-growatt ###
#########################################################################################################
### Made for Growatt MOD 10k TL3-X
#########################################################################################################

#########################################################################################################
### Functioning - Work In Progress
#########################################################################################################

esphome:
  name: '${device_name}'
  comment: '${device_description}'

#Developed on a ESP32-S3-WROOM N16R8 Board with a TTL to RS485 Board with Auto Flow Control
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

psram:
  mode: octal

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret growatt-mod-10k-tl3-x_api-encryption-key
    
ota:
  - platform: esphome
    password: !secret growatt-mod-10k-tl3-x_ota-password
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growatt-Mod-10K-Tl3-X"
    password: "vxYHcWnGpysu"

captive_portal:


time:
  - platform: homeassistant
    id: homeassistant_time

#Board contains an adressable neopixel.
#TODO: Enable state signalling via the pixel
#output:
# Blue Led
#  - id: light_bl
#    platform: gpio
#    pin: 16
# Green Led
#  - id: light_gr
#    platform: gpio
#    pin: 0
# Red Led
#  - id: light_rd
#    platform: gpio
#    pin: 2

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  #baud_rate: 38400 #See Register 22 - cannot be changed in runtime
  stop_bits: 1
  #debug:
  #  direction: RX
  #  dummy_receiver: false
  #  after:
  #    delimiter: "\n"
  #  sequence:
  #    - lambda: UARTDebug::log_string(direction, bytes);

modbus:
  id: modbus1
  uart_id: mod_bus
# flow_control_pin: 4 #for use when you use a rs485 board without auto flow control. Like the rs485 max board.

modbus_controller:
  - id: ${modbus_controller_id}
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10  
    update_interval: ${modbus_update_interval}
    #TODO: the command_throttle setting seem to cause some "Duplicate modbus command found" messages, but it sees they cause no real issues
    command_throttle: 1000ms # Growatt documentation recommends 1s 


######################################################################################################################
# Setup for Growatt MOD 10k-TL3-X
######################################################################################################################
# TL3-X(MAX、MID、MAC Type)：03 register range：0~124,125~249； (The 03 registers are called "holding" registers. Often R/W)
# 04 register range：0~124,125~249 (The 04 registers are called "input" registes - read only)
# Reference doc: growatt-inverter-modbus-rtu-protocol-ii-v1-24-english-new_compress.pdf
######################################################################################################################
 
sensor:


    ##OK
  - platform: wifi_signal
    name: "Modbus WiFi Signal"
    update_interval: 60s

    ##OK
  - platform: modbus_controller
    name: "status_code"
    id: status
    skip_updates: $skip_updates_slow
    address: 0
    register_type: "read"
    internal: true
    accuracy_decimals: 0

    ##OK
  - platform: modbus_controller
    name: "Energy Today"
    skip_updates: $skip_updates_slow
    address: 53
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1


    ##OK
  - platform: modbus_controller
    name: "Energy Total"
    skip_updates: $skip_updates_slow
    address: 55
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    
 
  - platform: modbus_controller
    name: "Inverter Temperature"
    address: 93
    register_type: "read"
    unit_of_measurement: °C
    device_class: temperature
    entity_category: diagnostic
    icon: mdi:thermometer
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
    skip_updates: $skip_updates_slow




## Solar Energy - BEGIN ##

 ## Ppv H Input power (high)
  - platform: modbus_controller
    name: "Input Power (Ppv H)"
    address: 1
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1

 ## Ppv L Input power (low)
  - platform: modbus_controller
    name: "Input Power (Ppv L)"
    address: 2
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1


## Solar Energy - PV1 ##

  ##OK
  - platform: modbus_controller
    id: pv1_energy_today
    name: "PV1 Energy Today"
    address: 59
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power-variant
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  
  ##OK
  - platform: modbus_controller
    id: pv1_energy_total
    name: "PV1 Energy Total"
    skip_updates: $skip_updates_slow
    address: 61
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  ##OK
  - platform: modbus_controller
    name: "PV1 Voltage"
    address: 3
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:flash-triangle-outline
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
    - multiply: 0.1
    
  ##OK
  - platform: modbus_controller
    name: "PV1 Current"
    address: 4
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:current-dc
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  ##OK
  - platform: modbus_controller
    name: "PV1 Power"
    id: pv1_power
    address: 5
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:solar-power-variant
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1


## Solar Energy - PV2 ##

  
  ##OK
  - platform: modbus_controller
    id: pv2_energy_today
    name: "PV2 Energy Today"
    address: 63
    register_type: "read"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power-variant
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  
  
  ##OK
  - platform: modbus_controller
    id: pv2_energy_total
    name: "PV2 Energy Total"
    skip_updates: $skip_updates_slow
    address: 65
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  
  ##OK
  - platform: modbus_controller
    name: "PV2 Voltage"
    address: 7
    register_type: "read"
    unit_of_measurement: V
    device_class: voltage
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:flash-triangle-outline
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
    - multiply: 0.1
    
  
  ##OK
  - platform: modbus_controller
    name: "PV2 Current"
    address: 8
    register_type: "read"
    unit_of_measurement: A
    device_class: current
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:current-dc
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

  ##OK
  - platform: modbus_controller
    id: pv2_power
    name: "PV2 Power"
    address: 9
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    state_class: measurement
    icon: mdi:solar-power-variant
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1


## Solar Energy - Totals ##

  #Epv_total H
  - platform: modbus_controller
    id: pv_energy_total
    name: "${friendly_name} PV Energy Total"
    skip_updates: $skip_updates_slow
    address: 91
    register_type: "read"
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    icon: mdi:solar-power-variant
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1
  
  - platform: template
    id: pv_energy_today
    name: "${friendly_name} PV Energy Today"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    icon: mdi:solar-power-variant
    accuracy_decimals: 1
    lambda: |-
      return float((id(pv1_energy_today).state + id(pv2_energy_today).state));
    update_interval: ${update_slow}

  - platform: template
    id: pv_power
    name: "PV Power"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    icon: mdi:solar-power-variant
    accuracy_decimals: 0
    lambda: |-
      return float((id(pv1_power).state + id(pv2_power).state));
    update_interval: ${update_fast}

## Solar Energy - END ##


### ac input ### 


## ac output ##


  ## Pac H Output power (high)
  - platform: modbus_controller
    name: "Output Power (Pac H)"
    address: 35
    register_type: "read"
    unit_of_measurement: W
    device_class: power
    entity_category: diagnostic
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1

  ## Pac L Output power (Low)
  - platform: modbus_controller
    name: "Output Power (Pac L)"
    address: 36
    register_type: "read"
    unit_of_measurement: W
    entity_category: diagnostic
    device_class: power
    icon: mdi:solar-power
    value_type: U_DWORD
    accuracy_decimals: 0
    filters:
    - multiply: 0.1


## DC ##


  
select:


#### system Settings ###

    ### The inverter can be switched on and off, and the BDC can be switched on and off for the batt ready function. ### 
    ### Writable ###
  - platform: modbus_controller
    name: "${device_name} Inverter Operation Mode"
    icon: mdi:power
    ##id OnOff
    address: 00
    value_type: U_WORD
    optionsmap:
      "Inverter On": 1
      "Inverter Off": 0
    ##"BDC On": 3   ##Only valid for Battery Enabled Systems
    ##"BDC Off": 4  ##Only valid for Battery Enabled Systems


  - platform: modbus_controller
    name: "Maximum Active Power Output %"
    address: 03
    value_type: U_WORD
    optionsmap:  # 0 - 100, 255
      "0% (Output Diabled)": 0
      "10%": 10
      "20%": 20
      "30%": 30
      "40%": 40
      "50%": 50
      "60%": 60
      "70%": 70
      "80%": 80
      "90%": 90
      "100%": 100
      "Unlimited (Default)": 255

  - platform: modbus_controller
    name: "Maximum Reactive Power Output %"
    address: 04
    value_type: U_WORD
    optionsmap:  # 0 - 100, 255
      "0% (Output Diabled)": 0
      "10%": 10
      "20%": 20
      "30%": 30
      "40%": 40
      "50%": 50
      "60%": 60
      "70%": 70
      "80%": 80
      "90%": 90
      "100%": 100
      "Unlimited (Default)": 255


text_sensor:
  - platform: template
    name: "Status state"
    icon: mdi:eye
    entity_category: diagnostic
    lambda: |-
      uint16_t value = static_cast<uint16_t>(id(status).state);
      switch (value) {
        case 0:  return std::string("Standby");
        case 1:  return std::string("Normal");
        case 2:  return std::string("Discharge");
        case 3:  return std::string("Fault");
        case 4:  return std::string("Flash");
        case 5:  return std::string("PV Charging");
        case 6:  return std::string("AC Charging");
        case 7:  return std::string("Combined Charging");
        case 8:  return std::string("Combined Charging & Bypass");
        case 9:  return std::string("PV Charging & Bypass");
        case 10: return std::string("AC Charging & Bypass");
        case 11: return std::string("Bypass");
        case 12: return std::string("PV Charge and Discharge");
        default: 
          ESP_LOGW("WARNING", "Unexpected status_code value: %u", value); // Log unexpected values
          return std::string("Unknown");
      }

  - platform: modbus_controller
    name: "Fault code"
    skip_updates: ${skip_updates_10min}
    address: 105
    register_type: "read"
    icon: mdi:eye
    entity_category: diagnostic
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0:  return std::string("No error");
        case 24: return std::string("Auto test failed");
        case 25: return std::string("No AC connection");
        case 26: return std::string("PV isolation low");
        case 27: return std::string("Residual I high");
        case 28: return std::string("Output high DCI");
        case 29: return std::string("PV voltage high");
        case 30: return std::string("AC voltage out of range");
        case 31: return std::string("AC frequency out of range");
        case 32: return std::string("Module too hot");
        // case 1~23 " Error: 99+x
        default: 
          ESP_LOGW("WARNING", "Unexpected Fault code value: %u", value); // Log unexpected values
          return std::string("Fault code: " + to_string(value));
      }
      return x;
 
################################################################################################################################## 
 
 


